my_projects = [
    {"id": 1,
     "name": "Todo App",
     "description": "A basic todo apps, create a list and keep track of it in local storage.",
     "image": "https://github.com/nkp1111/frontend-mentor-challenges/blob/main/todo-app/src/assets/images/Screenshot"
              "%202022-11-27%20224353.png?raw=true",
     "github_link": "https://github.com/nkp1111/frontend-mentor-challenges/tree/main/todo-app",
     },
    {"id": 2,
     "name": "Easybank landing page",
     "description": "Landing page of Easybank",
     "image": "https://github.com/nkp1111/frontend-mentor-challenges/blob/main/easybank-landing-page/src/assets"
              "/images/Screenshot%202022-12-25%20195305.png?raw=true",
     "github_link": "https://github.com/nkp1111/frontend-mentor-challenges/tree/main/easybank-landing-page",
     },
    {"id": 3,
     "name": "Interactive comments section",
     "description": "Allows you write comment.",
     "image": "https://github.com/nkp1111/frontend-mentor-challenges/raw/main/interactive-comment-section/src/assets"
              "/images/Screenshot%202022-11-21%20104047.png",
     "github_link": "https://github.com/nkp1111/frontend-mentor-challenges/tree/main/interactive-comment-section",
     },
    {"id": 4,
     "name": "Static Job Listing",
     "description": "Filters job on job board according to the tags.",
     "image": "https://github.com/nkp1111/frontend-mentor-challenges/raw/main/static-job-listing/src/assets/images"
              "/Screenshot%202022-12-24%20174216.png",
     "github_link": "https://github.com/nkp1111/frontend-mentor-challenges/tree/main/static-job-listing",
     },
    {"id": 5,
     "name": "Tip Calculator",
     "description": "Calculate the total amount to pay with tip per person.",
     "image": "https://github.com/nkp1111/frontend-mentor-challenges/raw/main/tip-calculator-app-main/images"
              "/Screenshot%202022-10-30%20233536.png",
     "github_link": "https://github.com/nkp1111/frontend-mentor-challenges/tree/main/tip-calculator-app-main",
     },
    {"id": 6,
     "name": "And more...",
     "description": "Visit my GitHub accout.",
     "image": "https://github.com/nkp1111/html-css-javascript-Projects/blob/main/images/4-47096_cat-wallpaper-background-data-src-free-download-cat.jpg?raw=true",
     "github_link": "https://github.com/nkp1111",
     },
]
